Pair1/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views

app_name = "Pair1"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("index/<int:pk>", views.index1, name="index1"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("update/<int:pk>", views.update, name="update"),
    path("details/", views.details, name="details"),
    path("logins/", views.logins, name="logins"),
    # path('logins/', auth_views.LoginView.as_view(template_name='pair/logins.html'), name='logins'),
    path("Users/", views.Users, name="Users"),
]

pair/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Pair1.urls")),
]

Pair1/models.py
from ctypes.wintypes import CHAR
from django.db import models

class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)
class User(models.Model):
    user_id = models.CharField(max_length=32, unique=True, verbose_name='유저 아이디')
    user_pw = models.CharField(max_length=128, verbose_name='유저 비밀번호')
    user_name = models.CharField(max_length=16, unique=False, verbose_name='유저 이름')
    user_email = models.EmailField(max_length=128, unique=True, verbose_name='유저 이메일')
    user_register_dttm = models.DateTimeField(auto_now=True, verbose_name='계정 생성시간')

    def __str__(self):
        return self.user_name
    
    class Meta:
        db_table = 'user'
        verbose_name = '유저'
        verbose_name_plural = '유저'

Pair1/views.py
from importlib.resources import contents
import re
from django.shortcuts import render, redirect
from .models import Review, User
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

def index(request):
    k = Review.objects.all()
    context = {"c": k}
    return render(request, "Pair1/index.html", context)


def home(request):
    k = Review.objects.all()
    return redirect("Pair1:index")


def index1(request, pk):
    k = Review.objects.all()
    return redirect("Pair1:index")


def new(request):
    return render(request, "Pair1/new.html")


def create(request):
    k = request.GET
    v = [k[i] for i in k]
    Review.objects.create(title=v[0], content=v[1])
    return redirect("Pair1:index")


def detail(request, pk):
    k = Review.objects.get(pk=pk)
    context = {"c": k}
    return render(request, "Pair1/detail.html", context)
def details(request):
    k = Review.objects.latest('pk')
    context = {
        "c":k
    }
    return render(request,"Pair1/details.html",context)

def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect("Pair1:index")


def edit(request, pk):
    k = Review.objects.get(pk=pk)
    context = {"c": k}
    return render(request, "Pair1/edit.html", context)


def update(request, pk):
    r = Review.objects.get(pk=pk)

    title = request.GET.get("title")
    content = request.GET.get("content")

    r.title = title
    r.content = content

    r.save()
    return redirect("Pair1:detail", r.pk)
@csrf_exempt
def logins(request):
    if request.method == "GET":
        return render(request, 'Pair1/Users.html')
@csrf_exempt
def Users(request):
    if request.method == "GET":
        return render(request, 'Pair1/Users.html')
    elif request.method == "POST":
        user_id = request.POST.get('id', '')
        user_pw = request.POST.get('pw', '')
        user_pw_confirm = request.POST.get('pw-confirm', '')
        user_name = request.POST.get('name', '')
        user_email = request.POST.get('email', '')

        if (user_id or user_pw or user_pw_confirm or user_name or user_email) == "":
            return redirect('/Pair1/Users')
        elif user_pw != user_pw_confirm:
            return redirect('/Pair1/Users')
        else:
            user = User(
                user_id = user_id,
                user_pw = user_pw,
                user_name = user_name,
                user_email = user_email
            )
            user.save()
        return redirect('/')

Pair1/templates/pair1/Users.html
{% extends 'Pair1/base.html' %}
{% block content %}
<div>회원가입 페이지</div>
<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label for="id">아이디</label>
        <input type="text" id="id" placeholder="아이디를 입력하세요." name="id">
    </div>
    <div>
        <label for="id">비밀번호</label>
        <input type="password" id="pw" placeholder="비밀번호를 입력하세요." name="pw">
    </div>
    <div>
        <label for="pw-confirm">비밀번호 확인</label>
        <input type="password" id="pw-confirm" placeholder="비밀번호를 한 번 더 입력하세요." name="pw-confirm">
    </div>
    <div>
        <label for="name">이름</label>
        <input type="text" id="name" placeholder="이름를 입력하세요." name="name">
    </div>
    <div>
        <label for="email">이메일</label>
        <input type="email" id="email" placeholder="이메일를 입력하세요." name="email">
    </div>
    <button type="submit" name="register-submit" value="register">회원가입하기</button>
</form>
{% endblock %}

Pair1/templates/pair1/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, intial-scale=1.0">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
  <title>Document</title>
  <style>
    body,
    html {
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: rgba(255, 114, 96, 1);
      background: linear-gradient(45deg,
          rgba(255, 114, 96, 1) 0%,
          rgba(255, 114, 96, 1) 14%,
          rgba(252, 210, 113, 1) 54%,
          rgba(252, 210, 113, 1) 61%,
          rgba(102, 176, 102, 1) 93%,
          rgba(96, 135, 134, 1) 100%);
    }
  </style>

</head>

<body>
  <!-- header -->
    <nav class="navbar navbar-expand-lg bg-light sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Shark&Yeooness</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active fw-bold" aria-current="page" href="{% url 'Pair1:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active fw-bold" href="{% url 'Pair1:new' %}">리뷰작성</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active fw-bold" href="{% url 'Pair1:details' %}"> 최신 리뷰글 보기</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle fw-bold" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                기능목록
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'Pair1:home' %}">Home</a></li>
                <li><a class="dropdown-item" href="{% url 'Pair1:new' %}">리뷰작성</a></li>
                <li><a class="dropdown-item" href="{% url 'Pair1:details' %}"">최신 리뷰글 보기</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex mx-3" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
            <a class="nav-link" href="{% url 'Pair1:logins' %}">로그인</a>
            <a class="nav-link mx-3" href="{% url 'Pair1:Users' %}">회원 가입</a>
          </form>
        </div>
      </div>
    </nav>

  {% block content %}

  {% endblock %}
  <div class="row bg-black py-3 fixed-bottom">
    <footer class="text-center text-white col-12">copyright shark,yeooness</footer>
  </div>
</body>

</html>

Pair1/templates/pair1/detail.html
{% extends 'Pair1/base.html' %}

{% block content %}
<h1>제목:{{c.title}}</h1>
<p class="fs-3">{{ c.created_at |date:'Y-m-d' }}</p>
<!-- <img class="w-50" src="https://cdn.pixabay.com/photo/2017/11/24/10/43/ticket-2974645_1280.jpg" alt=""> -->
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label fs-1">리뷰내용</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3">{{c.content}}</textarea>
</div>

<div class="container d-flex justify-content-end">
  <a href="{% url 'Pair1:edit' c.pk %}"><button type="button" class="btn btn-success mx-1">수정</button></a>
  <a href="{% url 'Pair1:delete' c.pk %}"><button type="button" class="btn btn-danger mx-1">삭제</button></a>
  <a href="{% url 'Pair1:index1' c.pk %}"><button type="button" class="btn btn-dark mx-1">Home</a>
</div>
{% endblock %}

Pair1/templates/pair1/details.html
{% extends 'Pair1/base.html' %}

{% block content %}
<h1>제목:{{c.title}}</h1>
<p class="fs-3">{{ c.created_at |date:'Y-m-d' }}</p>
<!-- <img class="w-50" src="https://cdn.pixabay.com/photo/2017/11/24/10/43/ticket-2974645_1280.jpg" alt=""> -->
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label fs-1">리뷰내용</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3">{{c.content}}</textarea>
</div>

<div class="container d-flex justify-content-end">
  <a href="{% url 'Pair1:edit' c.pk %}"><button type="button" class="btn btn-success mx-1">수정</button></a>
  <a href="{% url 'Pair1:delete' c.pk %}"><button type="button" class="btn btn-danger mx-1">삭제</button></a>
  <a href="{% url 'Pair1:index1' c.pk %}"><button type="button" class="btn btn-dark mx-1">Home</a>
</div>
{% endblock %}

Pair1/templates/pair1/edit.html
{% extends 'Pair1/base.html' %}
{% block content %}
<form action="{% url 'Pair1:update' c.pk %}">
  <div class="input-group mb-3 me-3">
    <span class="input-group-text" id="basic-addon1">제목</span>
    <input name="title" type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1"
      value="{{c.title}}">
  </div>
  <div class="input-group mb-3 me-3">
    <span class="input-group-text" id="basic-addon1">내용</span>
    <input name="content" type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1"
      value="{{c.content}}">
  </div>
  <div class="d-grid">
    <button class="btn btn-outline-success col-12 my-3 py-3" type="submit">리뷰 수정</button>
  </div>
</form>
{% endblock %}

Pair1/templates/pair1/home.html
{% extends 'Pair1/base.html' %}

{% block content %}
<a href="{% url 'Pair1:new' %}">리뷰 작성</a>

<table class="table">
  <thead>
    <tr>
      <th scope="col">리뷰 번호</th>
      <th scope="col">리뷰 제목</th>
      <th scope="col">작성 시간</th>
    </tr>
  </thead>
  <tbody>
    {% for i in c %}
    <tr>
      <th scope="row">{{i.pk}}</th>
      <td><a href="{% url 'Pair1:detail' i.pk %}">{{i.title}}</a></td>
      <td>{{i.created_at |date:'Y-m-d'}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

Pair1/templates/pair1/index.html
{% extends 'Pair1/base.html' %}

{% block content %}

<!-- 리뷰 목록 -->
<div class="container my-5">
  <table class="table">
    <thead>
      <tr class="table-dark">
        <th scope="col">리뷰 번호</th>
        <th scope="col">리뷰 제목</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>
    <tbody>
      {% for i in c %}
      {% if i.pk >= 10 %}
      {% if i.pk|divisibleby:2 %}
      <tr class="table-success">
        <th scope="row">{{i.pk}}</th>
        <td><a href="{% url 'Pair1:detail' i.pk %}">{{i.title}}</a></td>
        <td>{{i.created_at |date:'Y-m-d'}}</td>
      </tr>
      {% elif not i.pk|divisibleby:2 %}
      <tr class="table-warning">
        <th scope="row">{{i.pk}}</th>
        <td><a href="{% url 'Pair1:detail' i.pk %}">{{i.title}}</a></td>
        <td>{{i.created_at |date:'Y-m-d'}}</td>
      </tr>
      {% endif %}
      {% endif %}
      {% endfor %}
    </tbody>
  </table>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
</div>


{% endblock %}

Pair1/templates/pair1/logins.html
{% extends 'Pair1/base.html' %}

{% block content %}
<form method="POST">
    <div>
        <label for="id">아이디</label>
        <input type="text" id="id" placeholder="아이디를 입력하세요." name="id">
    </div>
    <div>
        <label for="id">비밀번호</label>
        <input type="password" id="pw" placeholder="비밀번호를 입력하세요." name="pw">
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}

Pair1/templates/pair1/new.html
{% extends 'Pair1/base.html' %}

{% block content %}
<h1 class="text-center text-white">리뷰 작성</h1>
<form action="{% url 'Pair1:create' %}">
  <div class="input-group mb-3 me-3">
    <span class="input-group-text" id="basic-addon1">제목</span>
    <input name="title" type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3 me-3">
    <span class="input-group-text" id="basic-addon1">내용</span>
    <input name="content" type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1">
  </div>
  <div class="d-grid">
    <button class="btn btn-success col-12 my-3 py-3" type="submit">리뷰 작성</button>
  </div>
</form>
{% endblock %}